---
- name: Add ports to open on firewalld
  hosts: all
  become: yes
  gather_facts: true
  tasks:
    - name: Add port to firewalld
      firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
      loop:
        - 22/tcp
        - 80/tcp
        - 443/tcp

    - name: reload service firewalld
      systemd:
        name: firewalld
        state: reloaded
