---
- name: Patch RHEL
  hosts: inventory
  gather_facts: yes
  tasks:
    - name: "Security updates using the DNF module"
      dnf:
        name: "*"
        security: yes
        bugfix: yes
        state: latest
        update_cache: yes
        update_only: yes
      register: yum_update_status
      when: ansible_os_family == "RedHat"

    - name: "Remove packages not needed anymore"
      dnf:
        autoremove: yes
      when: ansible_os_family == "RedHat"

    - name: "Reboot when packages are updated"
      reboot:
      when: 
        - yum_update_status.changed
        - ansible_os_family == "RedHat"
